### ISSUE TITLE
caption my custom video

### ISSUE THREAD

**Issue by dawnlh** [ttengwang/PDVC#2]
Hi @ttengwang ~
Thanks for the sharing of your wonderful work! I want to caption my custom video, but unfortunately I find that most codes for captioning are starting from extracted features, and little instructions are provided for the extraction process. It's very inconvenient for me, cause I'm not so familiar with the captioning task, and I just want to utilize the tool for some applications. So could you please kindly give me some detailed instructions on how I can get the captions from a raw video? I will appreciate it a lot!

Thanks,
Zhihong

**Comment by ttengwang** [comment]
Hi @dawnlh , thanks for your interest in our work.

This repo BMT (https://github.com/v-iashin/BMT#details-on-feature-extraction) can deal with custom videos, it may meet your need.

For our paper, we directly download the C3D and TSN features from other repos rather than extract them by ourselves. The TSN features are provided by [densecap](https://github.com/salesforce/densecap#annotation-and-feature) using  [this repo](https://github.com/LuoweiZhou/anet2016-cuhk-feature). C3D features are provided by [ActivityNet Challenge](http://activity-net.org/challenges/2016/download.html#c3d) (no code).  I3D+VGGish features are from [BMT](https://github.com/v-iashin/BMT#details-on-feature-extraction). You can find the instructions in the above repos. 

I noticed the inconvenience for industrial applications and plan to add the feature extraction part in my spare time, but it won't be done very soon.

**Comment by dawnlh** [comment]
Thanks a lot for your detailed advice 🤝 . BMT does provide detailed instructions on how to deal with custom videos, but unfortunately, my video has no audio information, which BMT needs. I will try to figure out this problem~ And also, looking forward to the feature extraction part for PDVC, and thanks for your effort to make it convenient for real applications!

**Comment by ttengwang** [comment]
@dawnlh Hi, now this repo supports captioning custom videos.

**Comment by dawnlh** [comment]
> @dawnlh Hi, now this repo supports captioning custom videos.
Wonderful！ Much thanks for your effort and kind reminder!
